INSERT INTO BOOK (ID,NAME,AVAILABILITY) VALUES (1,'THE TWILIGHT - NEW MOON', 63);
INSERT INTO BOOK (ID,NAME,AVAILABILITY) VALUES (2,'THE TWILIGHT - ECLIPSE', 27);
INSERT INTO BOOK (ID,NAME,AVAILABILITY) VALUES (3,'HARRY POTTER AND THE GOBLET OF FIRE', 50);

